CREATE TABLE Users (
ID INT PRIMARY KEY AUTO_INCREMENT,
UserName VARCHAR(50) UNIQUE NOT NULL CHECK(UserName != ''),
Email VARCHAR(50) UNIQUE NOT NULL CHECK(Email != ''),
Password VARCHAR(50) NOT NULL CHECK(Password != ''));

CREATE TABLE Admins (
ID INT PRIMARY KEY AUTO_INCREMENT,
AdminName VARCHAR(50) UNIQUE NOT NULL CHECK(AdminName != ''),
Email VARCHAR(50) UNIQUE NOT NULL CHECK(Email != ''),
Password VARCHAR(50) NOT NULL CHECK(Password != ''));

CREATE TABLE Programs (ID INT PRIMARY KEY AUTO_INCREMENT,
User_ID INT REFERENCES Users(ID) ON DELETE SET NULL ON UPDATE CASCADE,
ProgramName VARCHAR(100) NOT NULL CHECK(ProgramName != ''),
Code TEXT,
CodeLanguage VARCHAR(50) NOT NULL CHECK(CodeLanguage != ''),
Tags VARCHAR(400),
PublicationDate DATE NOT NULL,
Moderator_ID INT REFERENCES Admins(ID) ON DELETE SET NULL ON UPDATE CASCADE,
ModerationDate DATE);